# MoveIt uses this configuration for controller management
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - right_arm_controller
    - right_gripper_controller
    - left_arm_controller
    - left_gripper_controller

  right_arm_controller:
    # 【关键修改】告诉 MoveIt 具体的 Action 名字
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - "j_51"
      - "j_52"
      - "j_53"
      - "j_54"
      - "j_55"
      - "j_56"

  right_gripper_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - "j_57"

  left_arm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - "j_1"
      - "j_2"
      - "j_3"
      - "j_4"
      - "j_5"
      - "j_6"

  left_gripper_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - "j_7"