# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

right_arm_controller:
  ros__parameters:
    joints:
      - "j_51"
      - "j_52"
      - "j_53"
      - "j_54"
      - "j_55"
      - "j_56"
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

right_gripper_controller:
  ros__parameters:
    joints:
      - "j_57"
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

left_arm_controller:
  ros__parameters:
    joints:
      - "j_1"
      - "j_2"
      - "j_3"
      - "j_4"
      - "j_5"
      - "j_6"
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

left_gripper_controller:
  ros__parameters:
    joints:
      - "j_7"
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity